repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        files: \.yml$

      - id: check-yaml
        args: [ --unsafe ]
        files: \.yml$

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.7
        files: src/.*\.py$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.241'
    hooks:
      - id: ruff
        language_version: python3.7
        files: src/.*\.py$
